###
GET http://127.0.0.1:8000/tasks


###
POST http://127.0.0.1:8000/task
Content-Type: application/json

{
  "name": "買晚餐"
}


###
PUT http://127.0.0.1:8000/task/3
Content-Type: application/json

{
  "name": "買早餐",
  "status": 1,
  "id": 3
}


###
DELETE http://127.0.0.1:8000/task/3
